name: Build executable
run-name: Build
on: [push]
jobs:
  build-and-upload:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: mlugg/setup-zig@v1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          zig build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: new-utils-${{ matrix.os }}
          path: ${{ github.workspace }}/zig-out
